# - name: "install {{component}}"
#   hosts: "{{component}}"
#   become: yes
#   roles:
#   - "{{component}}"


- name: Install {{ component }}
  hosts: "{{ component }}"
  become: yes
  roles:
    - "{{ component }}"
