- name: "copy {{component}} service" 
  ansible.builtin.copy:
    src: "{{component}}.service.j2"
    dest: "/etc/systemd/system/{{component}}.service.j2"

- name: demon reload 
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: "start and enable {{component}}" 
  ansible.builtin.service:
    name: "{{component}}"
    enabled: yes
    state: restarted
    